apiVersion: apps/v1
kind: Deployment
metadata:
  name: glory
  labels:
    app: glory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glory
  template:
    metadata:
      labels:
        app: glory
    spec:
      containers:
        - name: glory
          image: ghcr.io/molinfo-vienna/glory:latest
          command: ["/env/bin/nerdd_prediction_server"]
          resources:
            requests:
              cpu: 10m
              memory: 1Gi
            limits:
              cpu: "4"
              memory: 10Gi
          volumeMounts:
            - name: data
              mountPath: "/data"
      imagePullSecrets:
        - name: ghcr-secret
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-media
