apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-static
  labels:
    app: traefik
data:
  traefik.yml: |
    global:
      checkNewVersion: true
      sendAnonymousUsage: false
    entryPoints:
      metrics:
        address: :9100
      traefik:
        address: :8080
      web:
        address: :8000
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
      websecure:
        address: :8443
        http:
          tls: true
    providers:
      kubernetesCRD:
        allowEmptyServices: true
      kubernetesIngress:
        allowEmptyServices: true
        ingressEndpoint:
          publishedService: traefik/traefik
    api:
      dashboard: true
      basePath: /traefik
    ping:
      entryPoint: traefik
    metrics:
      prometheus: 
        entryPoint: metrics
    log:
      level: INFO
    certificatesResolvers:
      default:
        acme:
          storage: /data/acme.json
          tlsChallenge: {}
          
          